name: Running Code Coverage
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11
    - name: Upgrade pip and setuptools
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
    - name: Install dependencies
      run: |
        pip install pytest-cov
        echo requirements installed
    - name: Install Tokenizers
      run: |
        pip install wheel
        pip install tokenizers
        pip install netifaces
    - name: Run the tests
      run: |
          pip install -r requirements.txt
          pytest --cov=./

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
