name: Running Code Coverage
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Python 3.10.15
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.15
    - name: Install dependencies
      run: |
        pip install pytest-cov
        echo requirements installed
    - name: Run the tests
      env:
        SCRAPEOPS_API_SECRET: ${{ secrets.SCRAPEOPS_API_SECRET }}
      run: |
          pip install -r requirements.txt
          python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords'); nltk.download('vader_lexicon')"
          pytest --cov=./ --cov-config=test/.coveragerc --cov-report=xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        verbose: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
